# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd/api/authpb/auth.proto

require 'google/protobuf'


descriptor_data = "\n\x1a\x65tcd/api/authpb/auth.proto\x12\x06\x61uthpb\"%\n\x0eUserAddOptions\x12\x13\n\x0bno_password\x18\x01 \x01(\x08\"^\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\x10\n\x08password\x18\x02 \x01(\x0c\x12\r\n\x05roles\x18\x03 \x03(\t\x12\'\n\x07options\x18\x04 \x01(\x0b\x32\x16.authpb.UserAddOptions\"\x83\x01\n\nPermission\x12)\n\x08permType\x18\x01 \x01(\x0e\x32\x17.authpb.Permission.Type\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\x11\n\trange_end\x18\x03 \x01(\x0c\"*\n\x04Type\x12\x08\n\x04READ\x10\x00\x12\t\n\x05WRITE\x10\x01\x12\r\n\tREADWRITE\x10\x02\"?\n\x04Role\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12)\n\rkeyPermission\x18\x02 \x03(\x0b\x32\x12.authpb.PermissionB\x1fZ\x1dgo.etcd.io/etcd/api/v3/authpbb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Authpb
  UserAddOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authpb.UserAddOptions").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authpb.User").msgclass
  Permission = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authpb.Permission").msgclass
  Permission::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authpb.Permission.Type").enummodule
  Role = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authpb.Role").msgclass
end
