# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd/api/versionpb/version.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'


descriptor_data = "\n etcd/api/versionpb/version.proto\x12\tversionpb\x1a google/protobuf/descriptor.proto:>\n\x10\x65tcd_version_msg\x12\x1f.google.protobuf.MessageOptions\x18\xd0\x86\x03 \x01(\t\x88\x01\x01:>\n\x12\x65tcd_version_field\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\t\x88\x01\x01:<\n\x11\x65tcd_version_enum\x12\x1c.google.protobuf.EnumOptions\x18\xd2\x86\x03 \x01(\t\x88\x01\x01:G\n\x17\x65tcd_version_enum_value\x12!.google.protobuf.EnumValueOptions\x18\xd3\x86\x03 \x01(\t\x88\x01\x01\x42\"Z go.etcd.io/etcd/api/v3/versionpbb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Versionpb
end
