# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto

require 'google/protobuf'

require 'etcd/api/etcdserverpb/rpc_pb'


descriptor_data = "\n7etcd/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto\x12\x08v3lockpb\x1a\x1f\x65tcd/api/etcdserverpb/rpc.proto\"*\n\x0bLockRequest\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\r\n\x05lease\x18\x02 \x01(\x03\"I\n\x0cLockResponse\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.etcdserverpb.ResponseHeader\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"\x1c\n\rUnlockRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\">\n\x0eUnlockResponse\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.etcdserverpb.ResponseHeader2~\n\x04Lock\x12\x37\n\x04Lock\x12\x15.v3lockpb.LockRequest\x1a\x16.v3lockpb.LockResponse\"\x00\x12=\n\x06Unlock\x12\x17.v3lockpb.UnlockRequest\x1a\x18.v3lockpb.UnlockResponse\"\x00\x42:Z8go.etcd.io/etcd/server/v3/etcdserver/api/v3lock/v3lockpbb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module V3lockpb
  LockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v3lockpb.LockRequest").msgclass
  LockResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v3lockpb.LockResponse").msgclass
  UnlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v3lockpb.UnlockRequest").msgclass
  UnlockResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v3lockpb.UnlockResponse").msgclass
end
