# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd/api/mvccpb/kv.proto

require 'google/protobuf'


descriptor_data = "\n\x18\x65tcd/api/mvccpb/kv.proto\x12\x06mvccpb\"u\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x17\n\x0f\x63reate_revision\x18\x02 \x01(\x03\x12\x14\n\x0cmod_revision\x18\x03 \x01(\x03\x12\x0f\n\x07version\x18\x04 \x01(\x03\x12\r\n\x05value\x18\x05 \x01(\x0c\x12\r\n\x05lease\x18\x06 \x01(\x03\"\x91\x01\n\x05\x45vent\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.mvccpb.Event.EventType\x12\x1c\n\x02kv\x18\x02 \x01(\x0b\x32\x10.mvccpb.KeyValue\x12!\n\x07prev_kv\x18\x03 \x01(\x0b\x32\x10.mvccpb.KeyValue\" \n\tEventType\x12\x07\n\x03PUT\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x42\x1fZ\x1dgo.etcd.io/etcd/api/v3/mvccpbb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Mvccpb
  KeyValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mvccpb.KeyValue").msgclass
  Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mvccpb.Event").msgclass
  Event::EventType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mvccpb.Event.EventType").enummodule
end
