# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: etcd/api/etcdserverpb/rpc.proto for package 'etcdserverpb'

require 'grpc'
require 'etcd/api/etcdserverpb/rpc_pb'

module Etcdserverpb
  module KV
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'etcdserverpb.KV'

      # Range gets the keys in the range from the key-value store.
      rpc :Range, ::Etcdserverpb::RangeRequest, ::Etcdserverpb::RangeResponse
      # Put puts the given key into the key-value store.
      # A put request increments the revision of the key-value store
      # and generates one event in the event history.
      rpc :Put, ::Etcdserverpb::PutRequest, ::Etcdserverpb::PutResponse
      # DeleteRange deletes the given range from the key-value store.
      # A delete request increments the revision of the key-value store
      # and generates a delete event in the event history for every deleted key.
      rpc :DeleteRange, ::Etcdserverpb::DeleteRangeRequest, ::Etcdserverpb::DeleteRangeResponse
      # Txn processes multiple requests in a single transaction.
      # A txn request increments the revision of the key-value store
      # and generates events with the same revision for every completed request.
      # It is not allowed to modify the same key several times within one txn.
      rpc :Txn, ::Etcdserverpb::TxnRequest, ::Etcdserverpb::TxnResponse
      # Compact compacts the event history in the etcd key-value store. The key-value
      # store should be periodically compacted or the event history will continue to grow
      # indefinitely.
      rpc :Compact, ::Etcdserverpb::CompactionRequest, ::Etcdserverpb::CompactionResponse
    end

    Stub = Service.rpc_stub_class
  end
  module Watch
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'etcdserverpb.Watch'

      # Watch watches for events happening or that have happened. Both input and output
      # are streams; the input stream is for creating and canceling watchers and the output
      # stream sends events. One watch RPC can watch on multiple key ranges, streaming events
      # for several watches at once. The entire event history can be watched starting from the
      # last compaction revision.
      rpc :Watch, stream(::Etcdserverpb::WatchRequest), stream(::Etcdserverpb::WatchResponse)
    end

    Stub = Service.rpc_stub_class
  end
  module Lease
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'etcdserverpb.Lease'

      # LeaseGrant creates a lease which expires if the server does not receive a keepAlive
      # within a given time to live period. All keys attached to the lease will be expired and
      # deleted if the lease expires. Each expired key generates a delete event in the event history.
      rpc :LeaseGrant, ::Etcdserverpb::LeaseGrantRequest, ::Etcdserverpb::LeaseGrantResponse
      # LeaseRevoke revokes a lease. All keys attached to the lease will expire and be deleted.
      rpc :LeaseRevoke, ::Etcdserverpb::LeaseRevokeRequest, ::Etcdserverpb::LeaseRevokeResponse
      # LeaseKeepAlive keeps the lease alive by streaming keep alive requests from the client
      # to the server and streaming keep alive responses from the server to the client.
      rpc :LeaseKeepAlive, stream(::Etcdserverpb::LeaseKeepAliveRequest), stream(::Etcdserverpb::LeaseKeepAliveResponse)
      # LeaseTimeToLive retrieves lease information.
      rpc :LeaseTimeToLive, ::Etcdserverpb::LeaseTimeToLiveRequest, ::Etcdserverpb::LeaseTimeToLiveResponse
      # LeaseLeases lists all existing leases.
      rpc :LeaseLeases, ::Etcdserverpb::LeaseLeasesRequest, ::Etcdserverpb::LeaseLeasesResponse
    end

    Stub = Service.rpc_stub_class
  end
  module Cluster
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'etcdserverpb.Cluster'

      # MemberAdd adds a member into the cluster.
      rpc :MemberAdd, ::Etcdserverpb::MemberAddRequest, ::Etcdserverpb::MemberAddResponse
      # MemberRemove removes an existing member from the cluster.
      rpc :MemberRemove, ::Etcdserverpb::MemberRemoveRequest, ::Etcdserverpb::MemberRemoveResponse
      # MemberUpdate updates the member configuration.
      rpc :MemberUpdate, ::Etcdserverpb::MemberUpdateRequest, ::Etcdserverpb::MemberUpdateResponse
      # MemberList lists all the members in the cluster.
      rpc :MemberList, ::Etcdserverpb::MemberListRequest, ::Etcdserverpb::MemberListResponse
      # MemberPromote promotes a member from raft learner (non-voting) to raft voting member.
      rpc :MemberPromote, ::Etcdserverpb::MemberPromoteRequest, ::Etcdserverpb::MemberPromoteResponse
    end

    Stub = Service.rpc_stub_class
  end
  module Maintenance
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'etcdserverpb.Maintenance'

      # Alarm activates, deactivates, and queries alarms regarding cluster health.
      rpc :Alarm, ::Etcdserverpb::AlarmRequest, ::Etcdserverpb::AlarmResponse
      # Status gets the status of the member.
      rpc :Status, ::Etcdserverpb::StatusRequest, ::Etcdserverpb::StatusResponse
      # Defragment defragments a member's backend database to recover storage space.
      rpc :Defragment, ::Etcdserverpb::DefragmentRequest, ::Etcdserverpb::DefragmentResponse
      # Hash computes the hash of whole backend keyspace,
      # including key, lease, and other buckets in storage.
      # This is designed for testing ONLY!
      # Do not rely on this in production with ongoing transactions,
      # since Hash operation does not hold MVCC locks.
      # Use "HashKV" API instead for "key" bucket consistency checks.
      rpc :Hash, ::Etcdserverpb::HashRequest, ::Etcdserverpb::HashResponse
      # HashKV computes the hash of all MVCC keys up to a given revision.
      # It only iterates "key" bucket in backend storage.
      rpc :HashKV, ::Etcdserverpb::HashKVRequest, ::Etcdserverpb::HashKVResponse
      # Snapshot sends a snapshot of the entire backend from a member over a stream to a client.
      rpc :Snapshot, ::Etcdserverpb::SnapshotRequest, stream(::Etcdserverpb::SnapshotResponse)
      # MoveLeader requests current leader node to transfer its leadership to transferee.
      rpc :MoveLeader, ::Etcdserverpb::MoveLeaderRequest, ::Etcdserverpb::MoveLeaderResponse
      # Downgrade requests downgrades, verifies feasibility or cancels downgrade
      # on the cluster version.
      # Supported since etcd 3.5.
      rpc :Downgrade, ::Etcdserverpb::DowngradeRequest, ::Etcdserverpb::DowngradeResponse
    end

    Stub = Service.rpc_stub_class
  end
  module Auth
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'etcdserverpb.Auth'

      # AuthEnable enables authentication.
      rpc :AuthEnable, ::Etcdserverpb::AuthEnableRequest, ::Etcdserverpb::AuthEnableResponse
      # AuthDisable disables authentication.
      rpc :AuthDisable, ::Etcdserverpb::AuthDisableRequest, ::Etcdserverpb::AuthDisableResponse
      # AuthStatus displays authentication status.
      rpc :AuthStatus, ::Etcdserverpb::AuthStatusRequest, ::Etcdserverpb::AuthStatusResponse
      # Authenticate processes an authenticate request.
      rpc :Authenticate, ::Etcdserverpb::AuthenticateRequest, ::Etcdserverpb::AuthenticateResponse
      # UserAdd adds a new user. User name cannot be empty.
      rpc :UserAdd, ::Etcdserverpb::AuthUserAddRequest, ::Etcdserverpb::AuthUserAddResponse
      # UserGet gets detailed user information.
      rpc :UserGet, ::Etcdserverpb::AuthUserGetRequest, ::Etcdserverpb::AuthUserGetResponse
      # UserList gets a list of all users.
      rpc :UserList, ::Etcdserverpb::AuthUserListRequest, ::Etcdserverpb::AuthUserListResponse
      # UserDelete deletes a specified user.
      rpc :UserDelete, ::Etcdserverpb::AuthUserDeleteRequest, ::Etcdserverpb::AuthUserDeleteResponse
      # UserChangePassword changes the password of a specified user.
      rpc :UserChangePassword, ::Etcdserverpb::AuthUserChangePasswordRequest, ::Etcdserverpb::AuthUserChangePasswordResponse
      # UserGrant grants a role to a specified user.
      rpc :UserGrantRole, ::Etcdserverpb::AuthUserGrantRoleRequest, ::Etcdserverpb::AuthUserGrantRoleResponse
      # UserRevokeRole revokes a role of specified user.
      rpc :UserRevokeRole, ::Etcdserverpb::AuthUserRevokeRoleRequest, ::Etcdserverpb::AuthUserRevokeRoleResponse
      # RoleAdd adds a new role. Role name cannot be empty.
      rpc :RoleAdd, ::Etcdserverpb::AuthRoleAddRequest, ::Etcdserverpb::AuthRoleAddResponse
      # RoleGet gets detailed role information.
      rpc :RoleGet, ::Etcdserverpb::AuthRoleGetRequest, ::Etcdserverpb::AuthRoleGetResponse
      # RoleList gets lists of all roles.
      rpc :RoleList, ::Etcdserverpb::AuthRoleListRequest, ::Etcdserverpb::AuthRoleListResponse
      # RoleDelete deletes a specified role.
      rpc :RoleDelete, ::Etcdserverpb::AuthRoleDeleteRequest, ::Etcdserverpb::AuthRoleDeleteResponse
      # RoleGrantPermission grants a permission of a specified key or range to a specified role.
      rpc :RoleGrantPermission, ::Etcdserverpb::AuthRoleGrantPermissionRequest, ::Etcdserverpb::AuthRoleGrantPermissionResponse
      # RoleRevokePermission revokes a key or range permission of a specified role.
      rpc :RoleRevokePermission, ::Etcdserverpb::AuthRoleRevokePermissionRequest, ::Etcdserverpb::AuthRoleRevokePermissionResponse
    end

    Stub = Service.rpc_stub_class
  end
end
